#!/usr/local/bin/node

var fs = require('fs'),
    read = require('read'),
    bcrypt = require('bcrypt');

var BOOKMARKLET_TEMPLATE = "bookmarklet.js.template";
var BOOKMARK_TEMPLATE = "public/js/bookmark.js.template";
var CONFIG_TEMPLATE = "config.js.template";

read({prompt: "Host: "}, function(err, host) {
    read({prompt: "Password: ", silent: true}, function(err, pw) {
      read({prompt: "Auth Phrase: ", silent: true}, function(err, auth) {
        var password = bcrypt.encrypt_sync(pw, bcrypt.gen_salt_sync(10));
        var auth_token = bcrypt.encrypt_sync(auth, bcrypt.gen_salt_sync(10));

        // CONFIG
        var config = fs.readFileSync(CONFIG_TEMPLATE, "utf8");
        config = config.replace(/{{PASSWORD}}/, "'" + password + "'");
        config = config.replace(/{{AUTH_PHRASE}}/, "'" + auth_token+ "'");

        fs.writeFileSync(CONFIG_TEMPLATE.replace(".template", ""), config, "utf8");

        // BOOKMARKLET
        var bookmarklet = fs.readFileSync(BOOKMARKLET_TEMPLATE, "utf8");
        bookmarklet = bookmarklet.replace(/{{[^}]*}}/, host).replace(/[\s]/g, " ");

        fs.writeFileSync(BOOKMARKLET_TEMPLATE.replace(".template", ""), bookmarklet, "utf8");

        // BOOKMARK
        var bookmark = fs.readFileSync(BOOKMARK_TEMPLATE, "utf8");
        bookmark = bookmark.replace(/{{REPLACE_HOST}}/, host).replace(/{{AUTH_TOKEN}}/, "'" + auth_token+ "'");

        fs.writeFileSync(BOOKMARK_TEMPLATE.replace(".template", ""), bookmark, "utf8");
    });
});
});
